version: '3.8'

services:
  web:
    container_name: trend-backend
    image: "trend-backend/api"
    build:
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./:/workspace/trend-backend/
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    container_name: trend-backend-postgres-db
    image: postgis/postgis:14-3.4
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
    - "5432:5432"
    restart: on-failure
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "-h", "localhost",
        "-p", "5432",
        "-d", "$POSTGRES_DB",
        "-U", "$POSTGRES_USER"
      ]
      interval: 0.5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  postgres-data:
