# Generated by Django 4.2.16 on 2024-10-26 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='post.post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', '❤️ Love'), ('like', '👍 Like'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('crying', '😭 Crying'), ('disgusting', '🤮 Disgusting'), ('liar', '🤥 Liar'), ('angry', '😡 Angry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_reaction_per_user_per_post'),
        ),
    ]
