# Generated by Django 4.2.16 on 2024-09-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('love', '❤️ Love'), ('like', '👍 Like'), ('haha', '😂 Haha'), ('wow', '😮 Wow'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('thankful', '🙏 Thankful'), ('confused', '🤔 Confused'), ('surprised', '😲 Surprised'), ('disappointed', '😞 Disappointed'), ('excited', '🤩 Excited'), ('proud', '💪 Proud'), ('happy', '😊 Happy'), ('tired', '😫 Tired'), ('bored', '😒 Bored'), ('scared', '😱 Scared'), ('relieved', '😌 Relieved'), ('nervous', '😬 Nervous'), ('annoyed', '😖 Annoyed'), ('hopeful', '🤞 Hopeful'), ('curious', '🧐 Curious'), ('grateful', '🤗 Grateful'), ('inspired', '✨ Inspired'), ('determined', '😌 Determined'), ('amused', '😏 Amused'), ('frustrated', '😤 Frustrated'), ('content', '😊 Content'), ('lonely', '😔 Lonely'), ('optimistic', '🌞 Optimistic'), ('disgusted', '🤢 Disgusted'), ('shocked', '😧 Shocked'), ('anxious', '😟 Anxious'), ('relaxed', '😎 Relaxed'), ('confident', '💪 Confident'), ('stressed', '😓 Stressed'), ('embarrassed', '😳 Embarrassed'), ('pensive', '🤔 Pensive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_reactions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='vlog.video')),
            ],
            options={
                'unique_together': {('video', 'user', 'reaction_type')},
            },
        ),
    ]
