# Generated by Django 4.2.16 on 2024-10-26 05:34

import django.core.validators
from django.db import migrations, models
import vlog.models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_alter_video_video_alter_vlogreaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='vlogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm', '3gp']), vlog.models.validate_video_size]),
        ),
    ]
